**Домашнее задание 1**

Решите предложенные задания с использованием модуля NumPy. Использование условий и циклов крайне нежелательно (списковые включения это тоже цикл!), за это будут снижаться баллы.
Все задания равноценны. В каждой задаче постарайтесь придумать несколько решений. В задачах, где обязательно необходимо предложить хотя бы два решения, об этом написано. Решением должен быть Jupyter notebook / ссылка на Colab

Под массивом (если не указано иное), понимается одномерный массив. Для большей части задач не указан размер массива. Это значит, что код должен работать корректно для любого размера массива

1. Создайте массив 3x3, состоящий из True. Напишите минимум два варианта решения


In [1]:
import numpy as np
a = np.full((3, 3), True)
print(a)

b = [[True for _ in range(3)] for _ in range(3)]
print(b)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[True, True, True], [True, True, True], [True, True, True]]


2. Замените в массиве все нечетные положительные числа на -1

In [4]:
import numpy as np

a = np.array([[1, 2, 1], [-1, 5, -3], [7, 8, 6]])
a[(a > 0) & (a % 2 == 1)] = -1
print(a)

[[-1  2 -1]
 [-1 -1 -3]
 [-1  8  6]]


3. Найдите все числа, встречающиеся в 1 и 2 массивах

In [7]:
import numpy as np

a = np.array([1, 3, 5, 6])
b = np.array([2, 3, 4, 5, 7])
print(np.intersect1d(a, b))

[3 5]


4. Дана функция maxx, работающая с двумя числами. Напишите обертку над ней, которая будет работать с двумя np.array (одинакового размера) и будет применять функцию maxx поэлементно (вместо maxx может быть любая другая кастомная функция)


```
def maxx(x, y):
	    return x if x >= y else y
```




In [10]:
import numpy as np

def maxx(x, y):
    return x if x >= y else y
def maxx_array(a, b):
    vectorized_maxx = np.vectorize(maxx)
    return vectorized_maxx(a, b)

a = np.array([10, 1, 9, 3])
b = np.array([5, 3, 7, 4])
print(maxx_array(a, b))

[10  3  9  4]


5. Дана матрица 3х3. Поменяйте местами 1 и 2 столбцы матрицы.

In [46]:
import numpy as np

a = np.array([[1, 2, 3],  [4, 5, 6], [7, 8, 9]])
a[:, [0, 1]] = a[:, [1, 0]]
print(a)

[[2 1 3]
 [5 4 6]
 [8 7 9]]


6. Поменяйте опции (```np.set_printoptions```), чтобы при выводе numpy.array отображалось не более 6 элементов

In [48]:
import numpy as np

a = np.arange(10)
np.set_printoptions(threshold=6)
print(a)

[0 1 2 ... 7 8 9]


7. В данном массиве замените все числа, меньшие 0 на 0, а большие 255 на 255. Напишите минимум два варианта решения

In [19]:
import numpy as np

a = np.array([-10, 50, 260, 100, -5, 255, 300])
a = np.clip(a, 0, 255)
np.set_printoptions(threshold=100)
print(a)

[  0  50 255 100   0 255 255]


8. Выведите позиции топ-5 максимальных элементов в массиве. Попробуйте решить задачу за линейную сложность относительно числа элементов

In [22]:
import numpy as np

a = np.array([5, 32, 4, 35, 6, 6, 7, 100, 1000, 3])
b = np.argpartition(a, -5)[-5:]
print(*b[np.argsort(a[b])])

6 1 3 7 8


9. Преобразуйте массив массивов в одномерный массив.

In [25]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(*np.concatenate(a))

1 2 3 4


10. Найдите максимум в каждой строке двумерного массива

In [28]:
import numpy as np

a = np.array([[2, 1], [3, 4]])
print(*np.amax(a, axis=1))

2 4


11. Удалите все np.nan из массива

In [50]:
import numpy as np

a = np.array([1, 4, np.nan, 4, np.nan, 63, 7, np.nan])
print("Массив без np.nan:", a[~np.isnan(a)])

Массив без np.nan: [ 1.  4.  4. 63.  7.]


12. Найдите индекс пятого повторения числа 1 в массиве (считаем, что в массиве есть хотя бы пять единиц)

In [52]:
import numpy as np

a = np.array([1, 0, 0, 4, 1, 1, 4, 5, 6, 3, 1, 4, 3, 1, 1, 3, 4, 5, 11])
fifth_index = np.where(a == 1)[0][4]
print(fifth_index)

13


13. В квадратной матрице 5х5 из нулей получить ромб из 1, который касается середин сторон квадрата. Решите задачу как для полного ромба (внутри все 1), так и для полого (1 по границе, внутри 0):

```
полный           полый
0 0 1 0 0       0 0 1 0 0
0 1 1 1 0       0 1 0 1 0
1 1 1 1 1       1 0 0 0 1
0 1 1 1 0       0 1 0 1 0
0 0 1 0 0       0 0 1 0 0
```

In [37]:
import numpy as np

a = np.zeros((5, 5), dtype=int)

res1 = a.copy()
for i in range(5):
    for j in range(5):
        if abs(i - 2) + abs(j - 2) <= 2:
            res1[i, j] = 1

print("Полный:")
print(res1)
print()

res2 = a.copy()
for i in range(5):
    for j in range(5):
        if abs(i - 2) + abs(j - 2) == 2:
            res2[i, j] = 1
print("Полый:")
print(res2)

Полный:
[[0 0 1 0 0]
 [0 1 1 1 0]
 [1 1 1 1 1]
 [0 1 1 1 0]
 [0 0 1 0 0]]

Полый:
[[0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]]


14. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и удалить [3,5] колонки

In [40]:
import numpy as np

a = np.random.randint(1, 101, size=(5, 7))
print(a)
print()
print(np.delete(a, [3, 5], axis=1))

[[ 5 79 77 57 99 66 29]
 [86 62 28 96 29 58 44]
 [25 44  7 33 26 81 62]
 [72 11 27 73 75  8 34]
 [65 77 21 84 74 24 51]]

[[ 5 79 77 99 29]
 [86 62 28 29 44]
 [25 44  7 26 62]
 [72 11 27 75 34]
 [65 77 21 74 51]]


15. Вычислите [скользящее среднее](https://ru.wikipedia.org/wiki/%D0%A1%D0%BA%D0%BE%D0%BB%D1%8C%D0%B7%D1%8F%D1%89%D0%B0%D1%8F_%D1%81%D1%80%D0%B5%D0%B4%D0%BD%D1%8F%D1%8F) в окне ширины 3

In [43]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, -3, -10, -5])
w = np.ones(3) / 3
print(np.convolve(a, w, 'valid'))

[ 2.          3.          4.          2.         -2.66666667 -6.        ]
